### ISSUE TITLE
ui ignore the batchTime value in the contract when display the locked duration

### ISSUE THREAD

**Issue by orenyodfat** [dOrgTech/NectarDAO-Bootstrapper#6]
it alway shows the duration time in months units. 
![Screen Shot 2019-10-23 at 12 07 25](https://user-images.githubusercontent.com/5994398/67377279-1780f800-f58e-11e9-8196-81f62ce16181.png)

**Comment by tspoff** [comment]
Due to the resolution of days in the display mixed with the short values , this doesn't visually register changes except for very high durations. Works fine with prod values.
