### ISSUE TITLE
Display units for locked Nectar

### ISSUE THREAD

**Issue by plutoegg** [dOrgTech/NectarDAO-Bootstrapper#7]
Rather than exponential notation (see screenshot) it would be preferable to show the amounts with k, M units.

i.e 10.0k instead of 1.000e4

<img width="615" alt="Screenshot 2019-10-23 at 10 50 53" src="https://user-images.githubusercontent.com/22115014/67381022-257d4b80-f583-11e9-8e5d-dcfcafd92d7e.png">

**Comment by tspoff** [comment]
Add dots or commas as per financial number displays as well
